### ISSUE TITLE
GDR support

### ISSUE THREAD

**Issue by dearsxx0918** [ROCm/ROCK-Kernel-Driver#102]
I have take a look at https://github.com/rocmarchive/ROCnRDMA, it says that the module moved to kernel driver, but I installed the latest kernel driver, still can not use RDMA.
The command I used: `NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL NCCL_CROSS_NIC=3 NCCL_NET_GDR_READ=3 /home/test/install/ompi/bin/mpirun  -n 2  -x NCCL_IB_HCA=mlx5_0 -x UCX_TLS=rc,sm --mca  osc:rdma ucx -x UCX_NET_DEVICES=enp216s0f0,enp94s0f0 -display-map -display-topo  -host br-mgpu1:1,br-mgpu2:1  --display-allocation -output-filename log.log ./all_reduce_perf -g 2 -b 100 -e 400000`

 And what I found in the command output is 'NET/IB : GPU Direct RDMA Disabled for HCA 0 'mlx5_0'',
I dig into the rccl code, find the problem is 'moduleLoaded = (access("/sys/kernel/mm/memory_peers/amdkfd/version", F_OK) == -1) ? 0 : 1;'
And I checked the path, yes, it's not exist.

Someone can explain or help me on this question?

**Comment by fxkamd** [comment]
You may want to post this question on the RCCL repository. I'm  not familiar with the /sys/kernel/mm/memory_peers interface. I think this should come from the network driver after registering itself with amdgpu.

Note that you need DKMS drivers for both amdgpu/KFD and the Melanox NIC. The RDMA interface between those drivers is not available in the upstream drivers.
