### ISSUE TITLE
Machine crash during multi-gpu ML inference

### ISSUE THREAD

**Issue by boniek83** [ROCm/ROCK-Kernel-Driver#111]
Gist below contains dmesg just before machine became unresponsive.
dmesg: https://gist.github.com/boniek83/6b7bce76b531f59e8b5b98a6b7cae76a
Centos 7 (3.10.0-1160.21.1.el7.x86_64)
ROCK 3.5
4x Radeon VII
pytorch 1.6 + torchserve

**Comment by ppanchad-amd** [comment]
@boniek83 Apologies for the lack of response. Please check if your issue still exist with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by boniek83** [comment]
It works with newer driver.
