### ISSUE TITLE
Is it possible to close /dev/kfd from high-level interface?

### ISSUE THREAD

**Issue by ghostplant** [ROCm/ROCK-Kernel-Driver#123]
This is an example of the code:
```cpp
hipSetDevice(0);
hipLaunchKernel(...);
hipDeviceReset();

// Do other CPU things that is no longer related to GPU
...
...
```

We want something like `hipDeviceReset` to close any fd/mmap connections with `/dev/kfd` & `/dev/dri/xxxxx`. How is it possible?

**Comment by ppanchad-amd** [comment]
@ghostplant Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@ghostplant Closing ticket due to lack of activity.  Please free to re-open ticket if you still need assistance. Thanks!
