### ISSUE TITLE
Build kernel failed for testing CRIU

### ISSUE THREAD

**Issue by malixian** [ROCm/ROCK-Kernel-Driver#132]
Based on #125, I download the kernel for CRIU on [ https://gitlab.freedesktop.org/agd5f/linux]().   
My build command follows:
1. make oldconfig 
2. make prepare
3. make scripts
4. make M=drivers/gpu/drm/amd/amdgpu/ -j8

Finally, the build errror is:

> WARNING: Symbol version dump "Module.symvers" is missing.
>          Modules may not have dependencies or modversions.
>          You may get many unresolved symbol warnings.
>   MODPOST drivers/gpu/drm/amd/amdgpu/Module.symvers
> WARNING: modpost: "module_layout" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "pm_genpd_init" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "_copy_to_user" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "preempt_count_add" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "drm_dp_link_train_channel_eq_delay" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "perf_trace_buf_alloc" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "dma_fence_context_alloc" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "drm_atomic_helper_plane_reset" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "dma_fence_chain_ops" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: "drm_atomic_get_private_obj_state" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
> WARNING: modpost: suppressed 897 unresolved symbol warnings because there were too many)
> make[2]: *** No rule to make target 'scripts/module.lds', needed by 'drivers/gpu/drm/amd/amdgpu/amdgpu.ko'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
>   CC [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.mod.o
> scripts/Makefile.modpost:140: recipe for target '__modpost' failed
> make[1]: *** [__modpost] Error 2
> Makefile:1761: recipe for target 'modules' failed
> make: *** [modules] Error 2

I am a linux kernel noob, is there a way to solve this problem?

**Comment by ppanchad-amd** [comment]
@malixian Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
