### ISSUE TITLE
Compile on Debian 9 generate error

### ISSUE THREAD

**Issue by ghost** [ROCm/ROCK-Kernel-Driver#52]
I tried to compile and install driver with DKMS on Debian 9 kernel 4.9.0, but I receive this error:

    DKMS make.log for amdgpu-1.8-192 for kernel 4.9.0-7-amd64 (x86_64)
    Thu Aug  9 22:54:27 CEST 2018
    make: Entering directory '/usr/src/linux-headers-4.9.0-7-amd64'
      LD      /var/lib/dkms/amdgpu/1.8-192/build/built-in.o
      LD      /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/built-in.o    
      LD      /var/lib/dkms/amdgpu/1.8-192/build/amd/lib/built-in.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/lib/chash.o
      LD      /var/lib/dkms/amdgpu/1.8-192/build/scheduler/built-in.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/kcl_drm.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/main.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/scheduler/gpu_scheduler.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkcl/symbols.o
      LD      /var/lib/dkms/amdgpu/1.8-192/build/ttm/built-in.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/ttm/ttm_memory.o
      CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/scheduler/sched_fence.o
      LD      /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/built-in.o
     CC [M]  /var/lib/dkms/amdgpu/1.8-192/build/amd/amdkfd/kfd_module.o
    In file included from /var/lib/dkms/amdgpu/1.8-192/build/scheduler/backport/backport.h:5:0,
                 from <command-line>:0:
    /var/lib/dkms/amdgpu/1.8-192/build/include/kcl/kcl_fence.h: In function ‘kcl_dma_fence_set_error’:
    /var/lib/dkms/amdgpu/1.8-192/build/include/kcl/kcl_fence.h:163:7: error: ‘struct fence’ has no member named ‘status’
      fence->status = error;
            ^~
    In file included from /var/lib/dkms/amdgpu/1.8-192/build/ttm/backport/backport.h:5:0,
                 from <command-line>:0:
    /var/lib/dkms/amdgpu/1.8-192/build/include/kcl/kcl_fence.h: In function ‘kcl_dma_fence_set_error’:
    /var/lib/dkms/amdgpu/1.8-192/build/include/kcl/kcl_fence.h:163:7: error: ‘struct fence’ has no member named ‘status’
      fence->status = error;
       ^~
      LD      /var/lib/dkms/amdgpu/1.8-192/build/amd/amdgpu/built-in.o
    In file included from /var/lib/dkms/amdgpu/1.8-192/build/scheduler/backport/backport.h:5:0,
                 from <command-line>:0:

Any suggestions for resolve the issue?

**Comment by kentrussell** [comment]
Can you try the 1.9 release and see if the issue persists?

**Comment by estevopaz** [comment]
Hi, installing rocm-dkms=1.9.211 from your debian report keep failing unfortunately:
* Missing VERSION_ID in /etc/os-release, fixed manually, debian doesn't provide this variable.
* Compilation for linux-image-4.17.0-0.bpo.3-amd64 and linux-image-4.18.0-2-amd64 crash:
```
root@white:~# cat /var/lib/dkms/amdgpu/1.9-224/build/make.log
DKMS make.log for amdgpu-1.9-224 for kernel 4.17.0-0.bpo.3-amd64 (amd64)
Wed Oct 24 11:51:24 CEST 2018
make: Entering directory '/usr/src/linux-headers-4.17.0-0.bpo.3-amd64'
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdkcl/kcl_drm.o
  CC [M]  /var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.o
/var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.c: In function ‘amdgpu_pmops_runtime_suspend’:
/var/lib/dkms/amdgpu/1.9-224/build/amd/amdgpu/amdgpu_drv.c:768:2: error: implicit declaration of function ‘vga_switcheroo_set_dynamic_switch’ [-Werror=implicit-function-declaration]
  vga_switcheroo_set_dynamic_switch(pdev, VGA_SWITCHEROO_OFF);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
* Compilation for linux-image-4.9.0-7-amd64 also crash, but because another different missing function in kernel, if you also want the log, ask me, I'm a bit bored about reboot.

Thanks a lot for your time,
if you need some support from my side, no problem, just ask, best,
Estevo.

**Comment by kentrussell** [comment]
A user seems to think that the 2.1 release has addressed this issue (https://www.mersenneforum.org/showthread.php?t=23150&page=2) , though a simple forum post isn't really all that conclusive. If 2.2 still doesn't work, I would recommend trying the regular amdgpupro driver and if it hits the same issue, raise a bug at http://bugs.freedesktop.org and get the kernel guys to fix it properly, that way we can ensure that things work out-of-the-box, and that each new release will have the fix too.
