### ISSUE TITLE
DKMS build fails on ubuntu derivatives

### ISSUE THREAD

**Issue by krrk** [ROCm/ROCK-Kernel-Driver#65]
The [DKMS] makefile fails to identify the ubuntu derivative I'm running (KDE Neon) and possibly other ubuntu derivatives because it looks for "ubuntu" as the ID in `/etc/os-release`; however the ID for KDE Neon is "neon". For more information see my issue at RadeonOpenCompute/ROCm#641.

[DKMS]: https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/dkms/Makefile

**Comment by ppanchad-amd** [comment]
@krrk Apologies for the lack of response. Do you still need assistance with this ticket? If not, please close the ticket. Thanks!
